import { useState } from "react";
import Layout from "../components/Layout";
import api from "../api/axios";
import jsPDF from "jspdf";

export default function Payslip() {
  const [month, setMonth] = useState("");
  const [data, setData] = useState(null);

  const fetchPayslip = async () => {
    try {
      const res = await api.get(`/payroll/my/${month}`);
      setData(res.data);
    } catch {
      alert("Payslip not found");
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("PAYSLIP", 20, 20);

    doc.setFontSize(12);
    doc.text(`Employee Name: ${data.employee.name}`, 20, 40);
    doc.text(`Employee Code: ${data.employee.empCode}`, 20, 50);
    doc.text(`Month: ${data.month}`, 20, 60);
    doc.text(`Gross Salary: ₹${data.grossSalary}`, 20, 70);
    doc.text(`Deductions: ₹${data.deductions}`, 20, 80);
    doc.text(`Net Salary: ₹${data.netSalary}`, 20, 90);

    doc.text("Generated by Payroll Management System", 20, 115);

    doc.save(`Payslip_${data.employee.empCode}_${data.month}.pdf`);
  };

  return (
    <Layout>
      {/* Title */}
      <h2
        className="
          text-3xl font-extrabold mb-6 
          bg-gradient-to-r from-purple-300 to-blue-300 
          text-transparent bg-clip-text
        "
      >
        Payslip
      </h2>

      {/* Fetch Payslip Form */}
      <div
        className="
          bg-white/10 backdrop-blur-xl 
          border border-white/20 
          shadow-xl rounded-xl 
          p-6 max-w-md mb-10 
          animate-fadeIn
        "
      >
        <input
          type="month"
          className="glass-input mb-4"
          value={month}
          onChange={(e) => setMonth(e.target.value)}
        />

        <button
          onClick={fetchPayslip}
          className="
            w-full py-3 
            bg-gradient-to-r from-indigo-500 to-indigo-600 
            hover:scale-105 hover:opacity-90 
            text-white rounded-lg font-semibold 
            transition-all duration-300 shadow-lg shadow-indigo-500/30
          "
        >
          Fetch Payslip
        </button>
      </div>

      {/* Payslip Data */}
      {data && (
        <div
          className="
            bg-white/10 backdrop-blur-xl 
            border border-white/20 
            shadow-xl rounded-xl 
            p-8 max-w-md animate-fadeIn
          "
        >
          <p className="text-white/90"><b>Name:</b> {data.employee.name}</p>
          <p className="text-white/90"><b>Code:</b> {data.employee.empCode}</p>
          <p className="text-white/90"><b>Month:</b> {data.month}</p>
          <p className="text-white/90"><b>Gross Salary:</b> ₹{data.grossSalary}</p>
          <p className="text-white/90"><b>Deductions:</b> ₹{data.deductions}</p>
          <p className="text-white font-semibold text-green-300">
            <b>Net Salary:</b> ₹{data.netSalary}
          </p>

          {/* Download Button */}
          <button
            onClick={downloadPDF}
            className="
              mt-6 w-full py-3 
              bg-gradient-to-r from-red-500 to-red-600 
              hover:scale-105 hover:opacity-90 
              text-white rounded-lg font-semibold 
              transition-all duration-300 shadow-lg shadow-red-500/30
            "
          >
            Download PDF
          </button>
        </div>
      )}
    </Layout>
  );
}
