import { useState } from "react";
import Layout from "../components/Layout";
import api from "../api/axios";
import jsPDF from "jspdf";

export default function Payslip() {
  const [month, setMonth] = useState("");
  const [data, setData] = useState(null);

  const fetchPayslip = async () => {
    try {
      const res = await api.get(`/payroll/my/${month}`);
      setData(res.data);
    } catch {
      alert("Payslip not found");
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("PAYSLIP", 20, 20);

    doc.setFontSize(12);
    doc.text(`Employee Name: ${data.employee.name}`, 20, 40);
    doc.text(`Employee Code: ${data.employee.empCode}`, 20, 50);
    doc.text(`Month: ${data.month}`, 20, 60);
    doc.text(`Gross Salary: ₹${data.grossSalary}`, 20, 70);
    doc.text(`Deductions: ₹${data.deductions}`, 20, 80);
    doc.text(`Net Salary: ₹${data.netSalary}`, 20, 90);

    doc.text("Generated by Payroll Management System", 20, 115);

    doc.save(`Payslip_${data.employee.empCode}_${data.month}.pdf`);
  };

  return (
    <Layout>
      <h2 className="text-xl font-bold mb-4">Payslip</h2>

      <div className="bg-white p-6 shadow rounded max-w-md mb-6">

        <input
          type="month"
          className="border p-2 rounded w-full mb-3"
          value={month}
          onChange={(e) => setMonth(e.target.value)}
        />

        <button
          onClick={fetchPayslip}
          className="bg-indigo-600 hover:bg-indigo-700 text-white p-2 w-full rounded"
        >
          Fetch Payslip
        </button>
      </div>

      {data && (
        <div className="bg-white p-6 shadow rounded max-w-md">
          <p><b>Name:</b> {data.employee.name}</p>
          <p><b>Code:</b> {data.employee.empCode}</p>
          <p><b>Month:</b> {data.month}</p>
          <p><b>Gross Salary:</b> ₹{data.grossSalary}</p>
          <p><b>Deductions:</b> ₹{data.deductions}</p>
          <p><b>Net Salary:</b> ₹{data.netSalary}</p>

          <button
            onClick={downloadPDF}
            className="mt-4 bg-red-600 hover:bg-red-700 text-white p-2 rounded w-full"
          >
            Download PDF
          </button>
        </div>
      )}
    </Layout>
  );
}
